//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactsDatabaseEntities : DbContext
    {
        public ContactsDatabaseEntities()
            : base("name=ContactsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactsTable> ContactsTable { get; set; }
        public virtual DbSet<EmailsTable> EmailsTable { get; set; }
        public virtual DbSet<NumbersTable> NumbersTable { get; set; }
    }
}
